### ISSUE TITLE
docker-compose up -> containers exited with code 0

### ISSUE THREAD

**Issue by vdheuvel** [clementine-player/Buildbot#8]
I'm trying to use the buildbot to compile clementine for windows with ubuntu. I removed all the `slave-*`s except `slave-mingw` from `docker-compose.yml`, so I've got 3 containers left: `master`, `volumes` and `slave-mingw`.

I've managed to run docker-compose up without any errors. But the containers exit immediately:
```
$ sudo docker-compose up
Starting buildbot_volumes_1 ... 
Starting buildbot_volumes_1 ... done
Starting buildbot_master_1 ... 
Starting buildbot_master_1 ... done
Recreating buildbot_slave-mingw_1 ... 
Recreating buildbot_slave-mingw_1 ... done
Attaching to buildbot_volumes_1, buildbot_master_1, buildbot_slave-mingw_1
buildbot_volumes_1 exited with code 0
buildbot_slave-mingw_1 exited with code 0
buildbot_master_1 exited with code 0
```
Because `master` is down, I cannot access `http://localhost:8010/`.

I tried adding `tty: true` to each container in `docker-compose.yml` (was a suggestion on stackoverflow), this kept slave-mingw up but not the other two, so it didn't help me. How can I keep the docker containers up so I can access `http://localhost:8010/`?

**Comment by garciaadrian** [comment]
It seems that when the master container executes config/master/start.py buildbot fails to start. Here's some error messages from /persisdent-data/master/twistd.log

> 2017-10-05
 [-] Loading buildbot.tac...
2017-10-05 13:09:01+0000 [-] Loaded.
2017-10-05 13:09:01+0000 [-] twistd 17.9.0 (/usr/bin/python 2.7.12) starting up.
2017-10-05 13:09:01+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-10-05 13:09:01+0000 [-] Starting BuildMaster -- buildbot.version: 0.9.11
2017-10-05 13:09:01+0000 [-] Loading configuration from '/persistent-data/master/master.cfg'
2017-10-05 13:09:01+0000 [-] /persistent-data/master/master.cfg:11: buildbot.worker_transition.DeprecatedWorkerModuleWarning: 'buildbot.buildslave' module is deprecated, use 'buildbot.worker' module instead
2017-10-05 13:09:02+0000 [-] error while parsing config file:
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/config.py", line 181, in loadConfig
	    self.basedir, self.configFileName)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/config.py", line 139, in loadConfigDict
	    execfile(filename, localDict)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/compat.py", line 246, in execfile
	    exec(code, globals, locals)
	  File "/persistent-data/master/master.cfg", line 17, in <module>
	    from buildbot.status import html
	exceptions.ImportError: cannot import name html
2017-10-05 13:09:02+0000 [-] Configuration Errors:
2017-10-05 13:09:02+0000 [-]   error while parsing config file: cannot import name html (traceback in logfile)
2017-10-05 13:09:02+0000 [-] Halting master.
2017-10-05 13:09:02+0000 [-] BuildMaster startup failed
2017-10-05 13:09:02+0000 [-] BuildMaster is stopped
2017-10-05 13:09:02+0000 [-] Main loop terminated.
2017-10-05 13:09:02+0000 [-] Server Shut Down.

**Comment by garciaadrian** [comment]
So I looked at the buildbot API and found that this project uses the 0.8.x API but pip installs 0.9.x buildbot which has some breaking API changes and is why the master container exits. 

I've modified master.cfg.py to use the 0.9.x API and will see how that goes, meanwhile you can change buildbot to buildbot==0.8.14 in /master/Dockerfile

**Comment by hatstand** [comment]
You probably just want to use the docker image in slave-mingw/Dockerfile interactively. You don't need the rest of buildbot.
